### ISSUE TITLE
400 Bad Request CORS

### ISSUE THREAD

**Issue by mho-drouot** [wl-online-payments-direct/sdk-nodejs#2]
Client JS SDK: 2.0.0
Node.js SDK: onlinepayments-sdk-nodejs (npm) @ 3.2.0
==
![cors_bad_request](https://user-images.githubusercontent.com/105220578/167422594-d20b9d28-f845-456f-9ab1-c7f1ef9f0752.png)

After successfully creating a session, calling a promise (ex: getting payment products) returns an error (400 Bad Request).
```
session.getPaymentProduct(3, paymentDetails).then(product => { ... }, () => {...})
```

The same occurs with other APIs.

**Comment by worldline-direct-support-team** [comment]
Hi @mho-drouot, we're looking into this.

**Comment by mho-drouot** [comment]
Indeed. Topic closed.
