### ISSUE TITLE
Authorization error when using more then one instance

### ISSUE THREAD

**Issue by Ivanna-Nagirna** [wl-online-payments-direct/sdk-nodejs#3]
Hello,
The SDK works perfectly in case we use a single instance in our node application
But as soon as we initiate the second instance for requests to another Ingenico account (using `immutableInit` method) the first one brakes (`403 ACCESS_TO_MERCHANT_NOT_ALLOWED`).
Why? Well, it looks like for the requests it sends `Authorization` header of second instance. So as a result we have only one worked instance, the one that was initiated last.
Is there any workaround for this?

**Comment by worldline-direct-support-team** [comment]
Hi Ivanna! We're working on a fix for this which we expect to roll out soon. Unfortunately we cannot offer a work-around in the meantime.

Kind regards,
Worldline support team

**Comment by mho-drouot** [comment]
Hi, any news regarding the fix release date?  
We have as well to manage several groups, and we already set a software increment release objective in mid-August 2022...
Without the fix, we cannot integrate the SDK, and that could be troublesome for our next features (3DSV2 payment, etc.) 

Best of luck for the fix,
MH
