### ISSUE TITLE
AuthorizationError: ACCESS_TO_MERCHANT_NOT_ALLOWED when getting payment info.

### ISSUE THREAD

**Issue by uzun0ff** [wl-online-payments-direct/sdk-nodejs#5]
When trying to get details for a payment with `hostedcheckouts.get` call it always resolves to 

`  {
      "code": "9007",
      "id": "ACCESS_TO_MERCHANT_NOT_ALLOWED",
      "category": "DIRECT_PLATFORM_ERROR",
      "message": "ACCESS_TO_MERCHANT_NOT_ALLOWED",
      "httpStatusCode": 403
    }
`

I am using the same instance that I created for the `hostedcheckouts.create` so the configuration should not be wrong.

**Comment by worldline-direct-support-team** [comment]
Hello @uzun0ff,

Thank you for reaching out and providing details about the issue you are facing with our SDK. We have thoroughly reviewed your concerns and would like to gather more information to better understand your implementation.

Upon careful examination, we noticed that you mentioned the usage of the functions `hostedcheckouts.get` and `hostedcheckouts.create`. However, these functions do not exist in our SDK. The correct functions to use are `createHostedCheckout` and `getHostedCheckout` respectively.

To assist you further, we recommend referring to our comprehensive [SDK documentation](https://docs.direct.worldline-solutions.com/en/integration/basic-integration-methods/hosted-checkout-page) which provides clear explanations and code snippets on how to utilize these functions correctly.

Please let us know if the information provided was helpful or if you require further assistance. We are eager to offer more guidance based on the specifics of your implementation.

Best regards,
Worldline Online Payments Support Team

**Comment by uzun0ff** [comment]
Hmm, the `ConnectSdk` provides `hostedcheckouts` client with a `GET`/ `CREATE` methods in it, which I suppose should be substitute paths for  `createHostedCheckout`, `getHostedCheckout` and are using the same endpoints.

Essentially, those 2 comparisons should be equal and using the same `API`. 🤔

**Comment by worldline-direct-support-team** [comment]
Hello @uzun0ff,

Indeed, the hosted checkout methods for Direct differ from the Connect ones. The above mentioned methods, createHostedCheckout and getHostedCheckout correspond with the ones from Connect (create/get). 

In the documentation link provided in the previous reply it can be clearly seen that a different URL is used for the Direct and this might be something that can cause the issue. You can also provide us more info about your use case since it seems like you are trying to migrate to Direct. 

Best regards
Worldline Online Payment Support Team

**Comment by worldline-direct-support-team** [comment]
Hello @uzun0ff,

We would like to provide you with an update regarding the reported issue. It has come to our attention that we haven't received any feedback from you in the last three weeks. Based on this, we assume that our previous comment was helpful to you and that you were able to proceed with your integration process.

However, if you are still experiencing the issue or require further assistance, please do not hesitate to contact us. Our dedicated support team is available to provide you with the necessary support.

Best regards
Worldline Online Payment Support Team

**Comment by uzun0ff** [comment]
Hello and sorry for my late response!

I have managed to resolve the issue by switching from `connect-sdk` to `onlinepayments-sdk`.

Thanks for the help!

Best of luck,
Tsvetomir
